version: '3.8'
services:
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lakehouse

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin;
      mc mb minio/bronze --ignore-existing;
      mc mb minio/silver --ignore-existing;
      mc mb minio/gold --ignore-existing;
      echo 'Buckets created!';
      exit 0;
      "
    networks:
      - lakehouse
  
  spark-master-2:
    image: public.ecr.aws/bitnami/spark:3.5
    container_name: spark-master-2
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_OPTS=-Divy.home=/tmp/.ivy
      - HADOOP_USER_NAME=bitnami
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - .:/opt/bitnami/spark/app
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - lakehouse
      
  spark-worker-2:
    image: public.ecr.aws/bitnami/spark:3.5
    container_name: spark-worker-2
    user: root
    depends_on:
      - spark-master-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-2:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - HADOOP_USER_NAME=bitnami
    volumes:
      - .:/opt/bitnami/spark/app
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    networks:
      - lakehouse

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lakehouse

  airflow-webserver:
    image: apache/airflow:2.10.4
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow/app
      - _PIP_ADDITIONAL_REQUIREMENTS=vnstock pyarrow boto3 ipython pandas pyspark delta-spark
      - MINIO_ENDPOINT=http://minio:9000
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow/app
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: webserver
    networks:
      - lakehouse

  airflow-scheduler:
    image: apache/airflow:2.10.4
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow/app
      - _PIP_ADDITIONAL_REQUIREMENTS=vnstock pyarrow boto3 ipython pandas pyspark delta-spark
      - MINIO_ENDPOINT=http://minio:9000
    volumes:
      - .:/opt/airflow/app
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
    networks:
      - lakehouse

  airflow-init:
    image: apache/airflow:2.10.4
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=vnstock pyarrow boto3 ipython pandas pyspark delta-spark
    command: bash -c "airflow db init && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"
    networks:
      - lakehouse

networks:
  lakehouse:
    driver: bridge

volumes:
  postgres_data: